name: 'apple_store'
version: '0.5.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
vars:
  apple_store:
    app_store_app: "{{ ref('stg_apple_store__app_store_app') }}"
    sales_account: "{{ ref('stg_apple_store__sales_account') }}"
    sales_subscription_events: "{{ ref('stg_apple_store__sales_subscription_events') }}"
    sales_subscription_summary: "{{ ref('stg_apple_store__sales_subscription_summary') }}"
    apple_store_country_codes: "{{ ref('apple_store_country_codes') }}"
    app_store_discovery_and_engagement_detailed_daily: "{{ ref('stg_apple_store__app_store_discovery_and_engagement_daily')}}"
    app_crash_daily: "{{ ref('stg_apple_store__app_crash_daily')}}"
    app_store_download_detailed_daily: "{{ ref('stg_apple_store__app_store_download_daily')}}"
    app_session_detailed_daily: "{{ ref('stg_apple_store__app_session_daily')}}"
    app_store_installation_and_deletion_detailed_daily: "{{ ref('stg_apple_store__app_store_installation_and_deletion_daily')}}"
    apple_store__subscription_events:
    - 'Renew'
    - 'Cancel'
    - 'Subscribe'

models:
  apple_store:
    materialized: table
    +schema: apple_store
    intermediate:      
      +materialized: ephemeral
      reporting_grain:
        +materialized: table
