name: 'apple_store'
version: '0.1.0'
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

vars:
  apple_store:
    app: "{{ ref('stg_apple_store__app') }}"
    app_store_device_report: "{{ ref('stg_apple_store__app_store_device_report') }}"
    usage_device_report: "{{ ref('stg_apple_store__usage_device_report') }}"
    downloads_device_report: "{{ ref('stg_apple_store__downloads_device_report') }}"

    app_store_territory_report: "{{ ref('stg_apple_store__app_store_territory_report') }}"
    downloads_territory_report: "{{ ref('stg_apple_store__downloads_territory_report') }}"
    usage_territory_report: "{{ ref('stg_apple_store__usage_territory_report') }}"

    app_store_platform_version_report: "{{ ref('stg_apple_store__app_store_platform_version_report') }}"
    crashes_platform_version_device_report: "{{ ref('stg_apple_store__crashes_platform_version_device_report') }}"
    downloads_platform_version_report: "{{ ref('stg_apple_store__downloads_platform_version_report') }}"
    usage_platform_version_report: "{{ ref('stg_apple_store__usage_platform_version_report') }}"

    crashes_app_version_device_report: "{{ ref('stg_apple_store__crashes_app_version_device_report') }}"
    usage_app_version_report: "{{ ref('stg_apple_store__usage_app_version_report') }}"

    sales_account: "{{ ref('stg_apple_store__sales_account') }}"
    sales_subscription_event_summary: "{{ ref('stg_apple_store__sales_subscription_event_summary') }}"
    sales_subscription_summary: "{{ ref('stg_apple_store__sales_subscription_summary') }}"

    apple_store__using_subscriptions: true

    apple_store__subscription_events:
      - 'Renew'
      - 'Cancel'
      - 'Subscribe'
      - 'Start Introductory Offer'
      - 'Paid Subscription from Introductory Offer'
      - 'Reactivate'
      - 'Refund'
      - 'Crossgrade'
      - 'Upgrade'
      - 'Downgrade'

models:
  apple_search_ads:
    materialized: table
    +schema: apple_store
    intermediate:
      +materialized: ephemeral