config-version: 2

name: 'apple_store_integration_tests'
version: '0.5.0'

profile: 'integration_tests'

vars:
  # apple_store__using_subscriptions: True # un-comment this line when generating docs!
  apple_store_schema: apple_store_integration_tests_13
  apple_store_source:
    apple_store_app_identifier: "app_store_app"
    apple_store_sales_subscription_event_summary_identifier: "sales_subscription_event_summary"
    apple_store_sales_subscription_summary_identifier: "sales_subscription_summary"
    apple_store_discovery_and_engagement_detailed_daily_identifier: "app_store_discovery_and_engagement_detailed_daily"
    apple_store_crash_daily_identifier: "app_crash_daily"
    apple_store_download_detailed_daily_identifier: "app_store_download_detailed_daily"
    apple_store_session_detailed_daily_identifier: "app_session_detailed_daily"
    apple_store_installation_and_deletion_detailed_daily_identifier: "app_store_installation_and_deletion_detailed_daily"

    apple_store__subscription_events:
      - 'Renew'
      - 'Cancel'
      - 'Subscribe'

models:
  +persist_docs:
    relation: "{{ false if target.type in ('spark','databricks') else true }}"
    columns: "{{ false if target.type in ('spark','databricks') else true }}"
  +schema: "apple_store_{{ var('directed_schema','dev') }}" ## To be used for validation testing

seeds:
  apple_store_integration_tests:
      +quote_columns: "{{ true if target.type == 'redshift' else false }}"
      +column_types:
        _fivetran_synced: timestamp
        date: date

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']