config-version: 2

name: 'apple_store_integration_tests'
version: '1.3.0'

profile: 'integration_tests'

vars:
  # apple_store__using_subscriptions: True # @docs-include
  apple_store_schema: apple_store_integration_tests
  apple_store:
    apple_store_app_identifier: "app_store_app"
    apple_store_sales_subscription_event_summary_identifier: "sales_subscription_event_summary"
    apple_store_sales_subscription_summary_identifier: "sales_subscription_summary"
    apple_store_discovery_and_engagement_standard_daily_identifier: "app_store_discovery_and_engagement_standard_daily"
    apple_store_crash_daily_identifier: "app_crash_daily"
    apple_store_download_standard_daily_identifier: "app_store_download_standard_daily"
    apple_store_session_standard_daily_identifier: "app_session_standard_daily"
    apple_store_installation_and_deletion_standard_daily_identifier: "app_store_installation_and_deletion_standard_daily"

    apple_store__subscription_events:
      - 'Renew'
      - 'Cancel'
      - 'Subscribe'

models:
  +persist_docs:
    relation: true
    columns: "{{ false if target.type in ('databricks') else true }}"
  +schema: "apple_store_{{ var('directed_schema','dev') }}" ## To be used for validation testing

seeds:
  +docs:
    show: False
  apple_store_integration_tests:
      +quote_columns: "{{ target.type == 'redshift' or var('fivetran_using_source_casing', false) }}"
      app_crash_daily:
        +column_types:
          _fivetran_synced: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
          date: date
          app_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          crashes: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          unique_devices: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      app_session_standard_daily:
        +column_types:
          _fivetran_synced: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
          date: date
          app_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          sessions: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          total_session_duration: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          unique_devices: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      app_store_app:
        +column_types:
          _fivetran_synced: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
      app_store_discovery_and_engagement_standard_daily:
        +column_types:
          _fivetran_synced: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
          date: date
          app_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          counts: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          unique_counts: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      app_store_download_standard_daily:
        +column_types:
          _fivetran_synced: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
          date: date
          app_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          counts: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      app_store_installation_and_deletion_standard_daily:
        +column_types:
          _fivetran_synced: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
          date: date
          app_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          counts: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          unique_devices: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      sales_subscription_event_summary:
        +column_types:
          _fivetran_synced: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
          vendor_number: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          app_apple_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          subscription_apple_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          subscription_group_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          consecutive_paid_periods: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          previous_subscription_apple_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          days_before_canceling: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          days_canceled: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          quantity: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          paid_service_days_recovered: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      sales_subscription_summary:
        +column_types:
          _fivetran_synced: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
          date: date
          vendor_number: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          app_apple_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          subscription_apple_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          subscription_group_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          active_standard_price_subscriptions: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          active_free_trial_introductory_offer_subscriptions: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          active_pay_up_front_introductory_offer_subscriptions: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          active_pay_as_you_go_introductory_offer_subscriptions: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          free_trial_promotional_offer_subscriptions: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          pay_up_front_promotional_offer_subscriptions: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          pay_as_you_go_promotional_offer_subscriptions: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          marketing_opt_ins: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          billing_retry: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          grace_period: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          free_trial_offer_code_subscriptions: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          pay_up_front_offer_code_subscriptions: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          pay_as_you_go_offer_code_subscriptions: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
          subscribers: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

flags:
  send_anonymous_usage_stats: False
  use_colors: True
